source.. = src/
output.. = bin/
javacSource = 17
javacTarget = 17
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               recommendations.json,\
               icons/
